project:
  type: website
  output-dir: docs
  render:
    - feedback.qmd        
    - index.qmd           
    - next.qmd            
    - past.qmd            
    - past_scicom.qmd     
    - registration_faq.qmd
    - scicom.qmd  
    - local.qmd
    - speaker.qmd   
    - updates.qmd
    
website:
  title: "EFSPI regulatory statistics workshop"
  navbar:
    background: info
    left:
    - text: "2023 workshop"
      href: next.html
    - text: "Committees"
      menu:
        - text: "Local organizing committee"
          href: local.html
        - text: "Scientific committee"
          href: scicom.html
    - text: "Past workshops: programs, slidedecks, recordings"
      href: past.html
    - text: "Updates"
      href: updates.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source


